### ISSUE TITLE
NullPointerException with custom throwable in logstage

### ISSUE THREAD

**Issue by paulpdaniels** [7mind/izumi#1124]
This is just a heads up issue. I'm not sure if this is something that can be addressed by the library.

I noticed this first with the `Fetch` library and wrote it off as a strange pattern on the library side, but I recently ran into this again. In the case of a custom `Throwable` i.e.

```scala
sealed trait CalibanClientError extends Throwable with Product with Serializable

case class CommunicationError(msg: String, innerThrowable: Option[Throwable] = None) extends CalibanClientError
``` 

it seems to fail when I do something like this

```scala
log("userId" -> req.user.map(_.id)).info(s"Error processing GraphQL request $cause")
```

where `cause` is a `Cause[CalibanClientError]`

with an NPE:

```
java.lang.NullPointerException
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:320)
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:303)
	at io.circe.Json$JString.foldWith(Json.scala:359)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:370)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:303)
	at io.circe.Json$JObject.foldWith(Json.scala:421)
	at io.circe.JsonObject$MapAndVectorJsonObject.appendToFolder(JsonObject.scala:450)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:370)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:303)
	at io.circe.Json$JObject.foldWith(Json.scala:421)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:370)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:303)
	at io.circe.Json$JObject.foldWith(Json.scala:421)
	at io.circe.Printer.print(Printer.scala:194)
	at io.circe.Json.noSpaces(Json.scala:123)
	at izumi.logstage.api.rendering.json.LogstageCirceRenderingPolicy.dump(LogstageCirceRenderingPolicy.scala:53)
	at izumi.logstage.api.rendering.json.LogstageCirceRenderingPolicy.render(LogstageCirceRenderingPolicy.scala:46)
	at izumi.logstage.sink.ConsoleSink.flush(ConsoleSink.scala:9)
	at izumi.logstage.sink.QueueingSink.izumi$logstage$sink$QueueingSink$$doFlush(QueueingSink.scala:81)
	at izumi.logstage.sink.QueueingSink$$anon$1.run(QueueingSink.scala:37)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by neko-kai** [comment]
@paulpdaniels 
I'll look into it. Does this _only_ happen with JSON output or with text console output as well?

**Comment by paulpdaniels** [comment]
@neko-kai Not sure, haven't tried with normal console renderer. I'll see if I can replicate there.
